#!/usr/bin/env node
// Pull all sprite data from Supabase and overwrite shared/sprite-data.js
// Usage: node scripts/pull-sprites.js

import 'dotenv/config';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { BANK_PALETTE, BANK_SPRITE } from '../shared/sprite-data.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SPRITE_DATA_PATH = path.join(__dirname, '..', 'shared', 'sprite-data.js');

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Error: SUPABASE_URL and SUPABASE_SERVICE_KEY (or SUPABASE_KEY) required in .env');
  process.exit(1);
}

async function supabaseRequest(path) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1${path}`, {
    headers: {
      'apikey': SUPABASE_KEY,
      'Authorization': `Bearer ${SUPABASE_KEY}`,
    },
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GET ${path} failed (${res.status}): ${text}`);
  }
  return res.json();
}

async function main() {
  console.log('Pulling sprites from Supabase...');

  // Fetch all three sprite types in parallel
  const [breeds, decorations, shops] = await Promise.all([
    supabaseRequest('/custom_sprites?is_public=eq.true&select=breed_key,sprite_data,palette&order=updated_at.desc'),
    supabaseRequest('/decoration_sprites?select=dec_id,pixels,palette&order=dec_id'),
    supabaseRequest('/shop_sprites?select=shop_type,pixels,palette'),
  ]);

  if (!breeds.length) {
    console.error('No breed sprites found in DB. Aborting to avoid wiping local data.');
    process.exit(1);
  }

  // Deduplicate breeds — keep most recent per breed_key (already sorted by updated_at desc)
  const breedMap = new Map();
  let palette = null;
  for (const row of breeds) {
    if (!breedMap.has(row.breed_key)) {
      let sd = row.sprite_data;
      if (typeof sd === 'string') sd = JSON.parse(sd);
      breedMap.set(row.breed_key, sd);
      // Use palette from first breed (most recently updated)
      if (!palette && row.palette) palette = row.palette;
    }
  }

  console.log(`  Breeds: ${[...breedMap.keys()].join(', ')}`);
  console.log(`  Decorations: ${decorations.length}`);
  console.log(`  Shops: ${shops.length}`);

  // Build the file content
  const lines = [];
  lines.push('// Auto-generated by Dog Sprite Editor');
  lines.push('// Palette: 0=transparent, 1=body, 2=dark, 3=light, 4=black, 5=white, 6=pupil, 7=pink, 8=nose, 9-d=custom');
  lines.push('');
  lines.push(`export const SPRITE_PALETTE = ${JSON.stringify(palette)};`);
  lines.push('');

  // Write each breed as a named const
  const breedNames = [];
  for (const [key, spriteData] of breedMap) {
    breedNames.push(key);
    lines.push(`const ${key} = ${formatSpriteData(spriteData)};`);
    lines.push('');
  }

  // DOG_SPRITES export
  lines.push('export const DOG_SPRITES = {');
  lines.push('  ' + breedNames.join(',\n  ') + ',');
  lines.push('};');
  lines.push('');

  // ANIM_STATES
  const animStates = Object.keys(breedMap.values().next().value);
  lines.push(`export const ANIM_STATES = ${JSON.stringify(animStates)};`);
  lines.push('');

  // Decoration palettes and sprites
  const decPalettes = {};
  const decSprites = {};
  for (const row of decorations) {
    decPalettes[row.dec_id] = row.palette;
    decSprites[row.dec_id] = row.pixels;
  }
  lines.push(`export const DECORATION_PALETTES = ${JSON.stringify(decPalettes)};`);
  lines.push('');
  lines.push(`export const DECORATION_SPRITES = ${formatDecorationSprites(decSprites)};`);
  lines.push('');

  // Shop palettes and sprites
  const sPalettes = {};
  const sSprites = {};
  for (const row of shops) {
    sPalettes[row.shop_type] = row.palette;
    sSprites[row.shop_type] = row.pixels;
  }
  lines.push(`export const SHOP_PALETTES = ${JSON.stringify(sPalettes)};`);
  lines.push('');
  lines.push(`export const SHOP_SPRITES = ${formatDecorationSprites(sSprites)};`);
  lines.push('');

  // Bank sprite (not in DB — preserve from local file)
  lines.push('// Bank (stash box) sprite — same format as shop machines (2x2 tiles = 32x32 px)');
  lines.push(`export const BANK_PALETTE = ${JSON.stringify(BANK_PALETTE)};`);
  lines.push(`export const BANK_SPRITE = ${formatFrameArray(BANK_SPRITE)};`);
  lines.push('');

  fs.writeFileSync(SPRITE_DATA_PATH, lines.join('\n'));
  console.log(`\nWrote ${SPRITE_DATA_PATH}`);
}

// Format a breed's sprite data (object of anim state -> array of frames)
function formatSpriteData(data) {
  const entries = [];
  for (const [anim, frames] of Object.entries(data)) {
    const frameStrs = frames.map(frame => formatFrame(frame));
    entries.push(`  ${anim}: [${frameStrs.join(',')}]`);
  }
  return '{\n' + entries.join(',\n') + ',\n}';
}

// Format a single frame (array of 16 strings)
function formatFrame(frame) {
  const rows = frame.map(row => `    "${row}"`);
  return '[\n' + rows.join(',\n') + ',\n  ]';
}

// Format a flat array of strings (like BANK_SPRITE)
function formatFrameArray(arr) {
  const rows = arr.map(row => `  "${row}"`);
  return '[\n' + rows.join(',\n') + ',\n]';
}

// Format decoration/shop sprites (object of id -> array of strings)
function formatDecorationSprites(sprites) {
  const entries = [];
  for (const [id, pixels] of Object.entries(sprites)) {
    const rows = pixels.map(row => `    "${row}"`);
    entries.push(`  ${JSON.stringify(id)}: [\n${rows.join(',\n')},\n  ]`);
  }
  return '{\n' + entries.join(',\n') + ',\n}';
}

main().catch(err => {
  console.error('Pull failed:', err.message);
  process.exit(1);
});
